@push('plugin-scripts')
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.responsive.min.js"></script>
@endpush

@push('plugin-styles')
    <link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.11.5/css/responsive.dataTables.min.css" rel="stylesheet" />
@endpush

@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h4 class="mb-0">Wallet Recharge Codes</h4>
        <div>
            <button class="btn btn-success me-2" id="generateCodeBtn">
                <i class="material-icons-outlined">add</i>
                Generate Codes
            </button>
            <a href="{{ route('admin.wallet-codes.export') }}" class="btn btn-outline-primary">
                <i class="material-icons-outlined">download</i>
                Export
            </a>
        </div>
    </div>

    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <label for="statusFilter" class="form-label">Filter by Status:</label>
                    <select id="statusFilter" class="form-select">
                        <option value="">All Statuses</option>
                        <option value="unused">Unused</option>
                        <option value="used">Used</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <x-data-table title="Wallet Recharge Codes" table-id="wallet-codes-table"
            fetch-url="{{ route('admin.wallet-codes.data') }}" :columns="['Code', 'Balance', 'Status', 'Generated By', 'Used By', 'Created At', 'Used At', 'Actions']" :columns-config="[
                ['data' => 'code', 'name' => 'code'],
                ['data' => 'formatted_balance', 'name' => 'balance'],
                ['data' => 'status_badge', 'name' => 'status'],
                ['data' => 'generated_by_name', 'name' => 'generated_by'],
                ['data' => 'used_by_name', 'name' => 'used_by'],
                ['data' => 'formatted_created_at', 'name' => 'created_at'],
                ['data' => 'formatted_used_at', 'name' => 'used_at'],
                ['data' => 'action', 'name' => 'action', 'orderable' => false, 'searchable' => false],
            ]" />
    </div>

    <div class="modal fade" id="generateCodeModal" tabindex="-1" aria-labelledby="generateCodeModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="generateCodeModalLabel">Generate Wallet Codes</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="generateCodeForm">
                        <div class="mb-3">
                            <label for="balance" class="form-label">Balance Amount ($)</label>
                            <input type="number" class="form-control" id="balance" step="0.01" min="0.01"
                                required>
                            <div class="form-text">Amount that will be credited to the driver's wallet</div>
                        </div>
                        <div class="mb-3">
                            <label for="quantity" class="form-label">Number of Codes</label>
                            <input type="number" class="form-control" id="quantity" min="1" max="100"
                                value="1" required>
                            <div class="form-text">How many codes to generate (max: 100)</div>
                        </div>
                        <button type="submit" class="btn btn-primary">
                            <i class="material-icons-outlined">generate</i>
                            Generate Codes
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="generatedCodesModal" tabindex="-1" aria-labelledby="generatedCodesModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="generatedCodesModalLabel">Generated Codes</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success">
                        <i class="material-icons-outlined">check_circle</i>
                        Codes generated successfully! Share these codes with drivers.
                    </div>
                    <div id="generated-codes-list" class="table-responsive">
                    </div>
                    <div class="mt-3">
                        <button class="btn btn-outline-primary" id="copyAllCodes">
                            <i class="material-icons-outlined">content_copy</i>
                            Copy All Codes
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('custom-scripts')
    <script>
        $(document).on('TableReady', function() {
            function safeReload() {
                if (window.walletCodesTable && typeof window.walletCodesTable.ajax !== 'undefined') {
                    window.walletCodesTable.ajax.reload();
                } else {
                    console.warn("walletCodesTable is not ready yet.");
                }
            }

            $('#statusFilter').on('change', function() {
                const status = $(this).val();
                if (window.walletCodesTable) {
                    window.walletCodesTable.ajax.url('{{ route('admin.wallet-codes.data') }}?status=' +
                        status).load();
                }
            });

            $('#generateCodeBtn').click(function() {
                $('#generateCodeModal').modal('show');
            });

            $('#generateCodeForm').submit(function(e) {
                e.preventDefault();

                const formData = {
                    balance: $('#balance').val(),
                    quantity: $('#quantity').val()
                };

                $.ajax({
                    url: '{{ route('admin.wallet-codes.store') }}',
                    method: 'POST',
                    data: formData,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function(response) {
                        if (response.success) {
                            showToast('success', response.message);
                            $('#generateCodeModal').modal('hide');

                            let codesHtml = '<table class="table table-striped">';
                            codesHtml +=
                                '<thead><tr><th>Code</th><th>Balance</th></tr></thead><tbody>';
                            response.codes.forEach(function(code) {
                                codesHtml +=
                                    `<tr><td class="font-monospace">${code.code}</td><td>$${parseFloat(code.balance).toFixed(2)}</td></tr>`;
                            });
                            codesHtml += '</tbody></table>';

                            $('#generated-codes-list').html(codesHtml);
                            $('#generatedCodesModal').modal('show');
                            safeReload();
                        } else {
                            showToast('error', response.message || 'Failed to generate codes');
                        }
                    },
                    error: function(xhr, status, error) {
                        showToast('error', 'An error occurred while generating codes');
                    }
                });
            });

            $('#copyAllCodes').click(function() {
                const codes = [];
                $('#generated-codes-list tbody tr').each(function() {
                    const code = $(this).find('td:first').text();
                    codes.push(code);
                });

                const codesText = codes.join('\n');
                navigator.clipboard.writeText(codesText).then(function() {
                    showToast('success', 'All codes copied to clipboard!');
                }).catch(function() {
                    showToast('error', 'Failed to copy codes to clipboard');
                });
            });

            $('#generateCodeModal').on('hidden.bs.modal', function() {
                $('#generateCodeForm')[0].reset();
            });
        });
    </script>
@endpush
